package inventory.system;

import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

public class maingui extends javax.swing.JFrame {

    private Map<String, Security> userMap = InventorySystem.getSecurityMap();
    private Map<String, Item> inventoryMap = InventorySystem.getHashMap();

    public maingui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        list2 = new java.awt.List();
        sidepanel = new javax.swing.JPanel();
        Loginsidepanel = new javax.swing.JPanel();
        registersidepanelbutton = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Registrationsidepanel = new javax.swing.JPanel();
        loginsidepanelbutton1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Homesidepanel = new javax.swing.JPanel();
        Logouthomesidepanelbutton = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        optionssidepanel = new javax.swing.JPanel();
        Logoutoptionssidepanelbutton = new javax.swing.JToggleButton();
        additemoptionssidepanelbutton = new javax.swing.JToggleButton();
        removeitemoptionssidepanelbutton = new javax.swing.JToggleButton();
        inventoryoptionssidepanelbutton = new javax.swing.JToggleButton();
        orderrequestoptionssidepanelbutton = new javax.swing.JToggleButton();
        homeoptionssidepanelbutton = new javax.swing.JToggleButton();
        inventorysidepanel = new javax.swing.JPanel();
        additeminventorysidepanelbutton = new javax.swing.JToggleButton();
        removeiteminventorysidepanelbutton = new javax.swing.JToggleButton();
        orderrequestinventorysidepanelbutton = new javax.swing.JToggleButton();
        Logoutinventorysidepanelbutton1 = new javax.swing.JToggleButton();
        homeinventorysidepanelbutton = new javax.swing.JToggleButton();
        ordersidepanel = new javax.swing.JPanel();
        homeordersidepanelbutton = new javax.swing.JToggleButton();
        Logoutordersidepanelbutton = new javax.swing.JToggleButton();
        additemordersidepanelbutton = new javax.swing.JToggleButton();
        removeitemordersidepanelbutton = new javax.swing.JToggleButton();
        inventoryordersidepanelbutton = new javax.swing.JToggleButton();
        Parent = new javax.swing.JPanel();
        Loginpage = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        loginloginpagebutton = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        registrationpage = new javax.swing.JPanel();
        RegisterNameTextField = new javax.swing.JTextField();
        RegisterUIDTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        RegisterPasswordField = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        RegisterPasswordConfirmField = new javax.swing.JPasswordField();
        RegisterSaveButton = new javax.swing.JToggleButton();
        homepage = new javax.swing.JPanel();
        removeitemhomepagebutton = new javax.swing.JToggleButton();
        inventorystatushomepagebutton = new javax.swing.JToggleButton();
        additemhomepagebutton = new javax.swing.JToggleButton();
        orderrequesthomepagebutton = new javax.swing.JToggleButton();
        addoptionspage = new javax.swing.JPanel();
        addqtyaddoptionspage = new javax.swing.JToggleButton();
        additemaddoptionspage = new javax.swing.JToggleButton();
        addqtypage = new javax.swing.JPanel();
        list1 = new java.awt.List();
        jTextField4 = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        additempage = new javax.swing.JPanel();
        ITEMCODETextField = new javax.swing.JTextField();
        ITEMNAMETextField = new javax.swing.JTextField();
        SUPPLIERTextField = new javax.swing.JTextField();
        MOQSpinner = new javax.swing.JSpinner();
        PRICETextField = new javax.swing.JTextField();
        MINIMUMSpinner = new javax.swing.JSpinner();
        CreateNewItemButton = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        removeoptionspage = new javax.swing.JPanel();
        removeqtyremoveoptionspagebutton = new javax.swing.JToggleButton();
        removeitemremoveoptionspagebutton = new javax.swing.JToggleButton();
        removeqtypage = new javax.swing.JPanel();
        jSpinner4 = new javax.swing.JSpinner();
        list3 = new java.awt.List();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jToggleButton4 = new javax.swing.JToggleButton();
        removeitempage = new javax.swing.JPanel();
        list4 = new java.awt.List();
        jLabel22 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jToggleButton5 = new javax.swing.JToggleButton();
        inventorypage = new javax.swing.JPanel();
        list5 = new java.awt.List();
        jToggleButton6 = new javax.swing.JToggleButton();
        panel1 = new java.awt.Panel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        orderpage = new javax.swing.JPanel();
        list6 = new java.awt.List();
        jToggleButton7 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(640, 480));
        getContentPane().setLayout(null);

        sidepanel.setLayout(new java.awt.CardLayout());

        Loginsidepanel.setBackground(new java.awt.Color(102, 255, 255));

        registersidepanelbutton.setText("Register");
        registersidepanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registersidepanelbuttonActionPerformed(evt);
            }
        });

        jLabel1.setText("NEW USER?");

        jLabel2.setText("CLICK REGISTER TO SIGN UP");

        javax.swing.GroupLayout LoginsidepanelLayout = new javax.swing.GroupLayout(Loginsidepanel);
        Loginsidepanel.setLayout(LoginsidepanelLayout);
        LoginsidepanelLayout.setHorizontalGroup(
            LoginsidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginsidepanelLayout.createSequentialGroup()
                .addGroup(LoginsidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginsidepanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(LoginsidepanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1))
                    .addGroup(LoginsidepanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(registersidepanelbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LoginsidepanelLayout.setVerticalGroup(
            LoginsidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginsidepanelLayout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(registersidepanelbutton)
                .addGap(190, 190, 190))
        );

        sidepanel.add(Loginsidepanel, "card2");

        loginsidepanelbutton1.setText("Login");
        loginsidepanelbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginsidepanelbutton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("ALREADY REGISTERED");

        jLabel4.setText("Click on login");

        javax.swing.GroupLayout RegistrationsidepanelLayout = new javax.swing.GroupLayout(Registrationsidepanel);
        Registrationsidepanel.setLayout(RegistrationsidepanelLayout);
        RegistrationsidepanelLayout.setHorizontalGroup(
            RegistrationsidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrationsidepanelLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18))
            .addGroup(RegistrationsidepanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(RegistrationsidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RegistrationsidepanelLayout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(loginsidepanelbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );
        RegistrationsidepanelLayout.setVerticalGroup(
            RegistrationsidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrationsidepanelLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(230, Short.MAX_VALUE))
            .addGroup(RegistrationsidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RegistrationsidepanelLayout.createSequentialGroup()
                    .addGap(188, 188, 188)
                    .addComponent(loginsidepanelbutton1)
                    .addContainerGap(189, Short.MAX_VALUE)))
        );

        sidepanel.add(Registrationsidepanel, "card3");

        Logouthomesidepanelbutton.setText("LOG OUT");
        Logouthomesidepanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogouthomesidepanelbuttonActionPerformed(evt);
            }
        });

        jLabel5.setText("WELCOME BACK!!");

        javax.swing.GroupLayout HomesidepanelLayout = new javax.swing.GroupLayout(Homesidepanel);
        Homesidepanel.setLayout(HomesidepanelLayout);
        HomesidepanelLayout.setHorizontalGroup(
            HomesidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomesidepanelLayout.createSequentialGroup()
                .addGroup(HomesidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomesidepanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(Logouthomesidepanelbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HomesidepanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        HomesidepanelLayout.setVerticalGroup(
            HomesidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomesidepanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, Short.MAX_VALUE)
                .addComponent(Logouthomesidepanelbutton)
                .addGap(15, 15, 15))
        );

        sidepanel.add(Homesidepanel, "card4");

        Logoutoptionssidepanelbutton.setText("LOG OUT");
        Logoutoptionssidepanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutoptionssidepanelbuttonActionPerformed(evt);
            }
        });

        additemoptionssidepanelbutton.setText("ADD ITEM");
        additemoptionssidepanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additemoptionssidepanelbuttonActionPerformed(evt);
            }
        });

        removeitemoptionssidepanelbutton.setText("REMOVE ITEM");
        removeitemoptionssidepanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeitemoptionssidepanelbuttonActionPerformed(evt);
            }
        });

        inventoryoptionssidepanelbutton.setText("INVENTORY STATUS");
        inventoryoptionssidepanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryoptionssidepanelbuttonActionPerformed(evt);
            }
        });

        orderrequestoptionssidepanelbutton.setText("ORDER REQUEST");
        orderrequestoptionssidepanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderrequestoptionssidepanelbuttonActionPerformed(evt);
            }
        });

        homeoptionssidepanelbutton.setText("HOME");
        homeoptionssidepanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeoptionssidepanelbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionssidepanelLayout = new javax.swing.GroupLayout(optionssidepanel);
        optionssidepanel.setLayout(optionssidepanelLayout);
        optionssidepanelLayout.setHorizontalGroup(
            optionssidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionssidepanelLayout.createSequentialGroup()
                .addGroup(optionssidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionssidepanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(optionssidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inventoryoptionssidepanelbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(orderrequestoptionssidepanelbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removeitemoptionssidepanelbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(additemoptionssidepanelbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(optionssidepanelLayout.createSequentialGroup()
                        .addGroup(optionssidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(optionssidepanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(Logoutoptionssidepanelbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(optionssidepanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(homeoptionssidepanelbutton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        optionssidepanelLayout.setVerticalGroup(
            optionssidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionssidepanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(homeoptionssidepanelbutton)
                .addGap(66, 66, 66)
                .addComponent(additemoptionssidepanelbutton)
                .addGap(18, 18, 18)
                .addComponent(removeitemoptionssidepanelbutton)
                .addGap(18, 18, 18)
                .addComponent(inventoryoptionssidepanelbutton)
                .addGap(18, 18, 18)
                .addComponent(orderrequestoptionssidepanelbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(Logoutoptionssidepanelbutton)
                .addGap(23, 23, 23))
        );

        sidepanel.add(optionssidepanel, "card5");

        additeminventorysidepanelbutton.setText("ADD ITEM");
        additeminventorysidepanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additeminventorysidepanelbuttonActionPerformed(evt);
            }
        });

        removeiteminventorysidepanelbutton.setText("REMOVE ITEM");
        removeiteminventorysidepanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeiteminventorysidepanelbuttonActionPerformed(evt);
            }
        });

        orderrequestinventorysidepanelbutton.setText("ORDER REQUEST");
        orderrequestinventorysidepanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderrequestinventorysidepanelbuttonActionPerformed(evt);
            }
        });

        Logoutinventorysidepanelbutton1.setText("LOG OUT");
        Logoutinventorysidepanelbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logoutinventorysidepanelbutton1ActionPerformed(evt);
            }
        });

        homeinventorysidepanelbutton.setText("HOME");
        homeinventorysidepanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeinventorysidepanelbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inventorysidepanelLayout = new javax.swing.GroupLayout(inventorysidepanel);
        inventorysidepanel.setLayout(inventorysidepanelLayout);
        inventorysidepanelLayout.setHorizontalGroup(
            inventorysidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventorysidepanelLayout.createSequentialGroup()
                .addGroup(inventorysidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inventorysidepanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(inventorysidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(additeminventorysidepanelbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(removeiteminventorysidepanelbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(orderrequestinventorysidepanelbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(inventorysidepanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(Logoutinventorysidepanelbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(inventorysidepanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(homeinventorysidepanelbutton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inventorysidepanelLayout.setVerticalGroup(
            inventorysidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventorysidepanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(homeinventorysidepanelbutton)
                .addGap(88, 88, 88)
                .addComponent(additeminventorysidepanelbutton)
                .addGap(18, 18, 18)
                .addComponent(removeiteminventorysidepanelbutton)
                .addGap(18, 18, 18)
                .addComponent(orderrequestinventorysidepanelbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(Logoutinventorysidepanelbutton1)
                .addGap(21, 21, 21))
        );

        sidepanel.add(inventorysidepanel, "card6");

        homeordersidepanelbutton.setText("HOME");
        homeordersidepanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeordersidepanelbuttonActionPerformed(evt);
            }
        });

        Logoutordersidepanelbutton.setText("LOG OUT");
        Logoutordersidepanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutordersidepanelbuttonActionPerformed(evt);
            }
        });

        additemordersidepanelbutton.setText("ADD ITEM");
        additemordersidepanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additemordersidepanelbuttonActionPerformed(evt);
            }
        });

        removeitemordersidepanelbutton.setText("REMOVE ITEM");
        removeitemordersidepanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeitemordersidepanelbuttonActionPerformed(evt);
            }
        });

        inventoryordersidepanelbutton.setText("INVENTORY STATUS");
        inventoryordersidepanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryordersidepanelbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ordersidepanelLayout = new javax.swing.GroupLayout(ordersidepanel);
        ordersidepanel.setLayout(ordersidepanelLayout);
        ordersidepanelLayout.setHorizontalGroup(
            ordersidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ordersidepanelLayout.createSequentialGroup()
                .addGroup(ordersidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ordersidepanelLayout.createSequentialGroup()
                        .addGroup(ordersidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ordersidepanelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(homeordersidepanelbutton))
                            .addGroup(ordersidepanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(Logoutordersidepanelbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ordersidepanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ordersidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inventoryordersidepanelbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(removeitemordersidepanelbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(additemordersidepanelbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        ordersidepanelLayout.setVerticalGroup(
            ordersidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordersidepanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(homeordersidepanelbutton)
                .addGap(71, 71, 71)
                .addComponent(additemordersidepanelbutton)
                .addGap(18, 18, 18)
                .addComponent(removeitemordersidepanelbutton)
                .addGap(18, 18, 18)
                .addComponent(inventoryordersidepanelbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(Logoutordersidepanelbutton)
                .addGap(31, 31, 31))
        );

        sidepanel.add(ordersidepanel, "card7");

        getContentPane().add(sidepanel);
        sidepanel.setBounds(0, 0, 160, 400);

        Parent.setLayout(new java.awt.CardLayout());

        jTextField1.setText("jTextField1");

        jLabel6.setText("USER ID");

        jPasswordField1.setText("jPasswordField1");

        loginloginpagebutton.setText("Login");
        loginloginpagebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginloginpagebuttonActionPerformed(evt);
            }
        });

        jLabel7.setText("PASSWORD");

        javax.swing.GroupLayout LoginpageLayout = new javax.swing.GroupLayout(Loginpage);
        Loginpage.setLayout(LoginpageLayout);
        LoginpageLayout.setHorizontalGroup(
            LoginpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginpageLayout.createSequentialGroup()
                .addGroup(LoginpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginpageLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel6))
                    .addGroup(LoginpageLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(LoginpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)))
                    .addGroup(LoginpageLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(loginloginpagebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginpageLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel7)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        LoginpageLayout.setVerticalGroup(
            LoginpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginpageLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginloginpagebutton)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        Parent.add(Loginpage, "card2");

        RegisterNameTextField.setText("name");
        RegisterNameTextField.setName("RegisterNameTextField"); // NOI18N

        RegisterUIDTextField.setText("user id");

        jLabel8.setText("NAME");

        jLabel9.setText("USER ID");

        jLabel10.setText("PASSWORD");

        jLabel11.setText("RE-TYPE PASSWORD");

        RegisterSaveButton.setText("Register");
        RegisterSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterSaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registrationpageLayout = new javax.swing.GroupLayout(registrationpage);
        registrationpage.setLayout(registrationpageLayout);
        registrationpageLayout.setHorizontalGroup(
            registrationpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrationpageLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(registrationpageLayout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(registrationpageLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(registrationpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RegisterNameTextField)
                    .addComponent(RegisterUIDTextField)
                    .addComponent(RegisterPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(RegisterPasswordConfirmField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrationpageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RegisterSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrationpageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(205, 205, 205))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrationpageLayout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(183, 183, 183))
        );
        registrationpageLayout.setVerticalGroup(
            registrationpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrationpageLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RegisterNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RegisterUIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RegisterPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RegisterPasswordConfirmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(RegisterSaveButton)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        Parent.add(registrationpage, "card3");

        removeitemhomepagebutton.setText("REMOVE ITEM");
        removeitemhomepagebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeitemhomepagebuttonActionPerformed(evt);
            }
        });

        inventorystatushomepagebutton.setText("INVENTORY STATUS");
        inventorystatushomepagebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventorystatushomepagebuttonActionPerformed(evt);
            }
        });

        additemhomepagebutton.setText("ADD ITEM");
        additemhomepagebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additemhomepagebuttonActionPerformed(evt);
            }
        });

        orderrequesthomepagebutton.setText("ORDER REQUEST");
        orderrequesthomepagebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderrequesthomepagebuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout homepageLayout = new javax.swing.GroupLayout(homepage);
        homepage.setLayout(homepageLayout);
        homepageLayout.setHorizontalGroup(
            homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homepageLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(homepageLayout.createSequentialGroup()
                        .addComponent(inventorystatushomepagebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(orderrequesthomepagebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(homepageLayout.createSequentialGroup()
                        .addComponent(additemhomepagebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(removeitemhomepagebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
        );
        homepageLayout.setVerticalGroup(
            homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homepageLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeitemhomepagebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(additemhomepagebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inventorystatushomepagebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderrequesthomepagebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        Parent.add(homepage, "card4");

        addqtyaddoptionspage.setText("ADD QUANTITY");
        addqtyaddoptionspage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addqtyaddoptionspageActionPerformed(evt);
            }
        });

        additemaddoptionspage.setText("ADD NEW ITEM");
        additemaddoptionspage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additemaddoptionspageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addoptionspageLayout = new javax.swing.GroupLayout(addoptionspage);
        addoptionspage.setLayout(addoptionspageLayout);
        addoptionspageLayout.setHorizontalGroup(
            addoptionspageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addoptionspageLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(addqtyaddoptionspage, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(additemaddoptionspage, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        addoptionspageLayout.setVerticalGroup(
            addoptionspageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addoptionspageLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(addoptionspageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(additemaddoptionspage, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(addqtyaddoptionspage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        Parent.add(addoptionspage, "card5");

        jTextField4.setText("jTextField4");

        jLabel12.setText("ITEM CODE");

        jLabel13.setText("QUANTITY");

        jToggleButton1.setText("ADD QUANTITY");

        javax.swing.GroupLayout addqtypageLayout = new javax.swing.GroupLayout(addqtypage);
        addqtypage.setLayout(addqtypageLayout);
        addqtypageLayout.setHorizontalGroup(
            addqtypageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addqtypageLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel12)
                .addGap(53, 53, 53)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(addqtypageLayout.createSequentialGroup()
                .addGroup(addqtypageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addqtypageLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addqtypageLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jToggleButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addqtypageLayout.setVerticalGroup(
            addqtypageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addqtypageLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(addqtypageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addComponent(jToggleButton1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        Parent.add(addqtypage, "card6");

        ITEMCODETextField.setName("ITEMCODETextField"); // NOI18N

        CreateNewItemButton.setText("CREATE");
        CreateNewItemButton.setName("CREATEBUTTON"); // NOI18N
        CreateNewItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateNewItemButtonActionPerformed(evt);
            }
        });

        jToggleButton3.setText("REFRESH");

        jLabel14.setText("ITEM CODE");

        jLabel15.setText("ITEM NAME");

        jLabel16.setText("SUPPLIER");

        jLabel17.setText("MINIMUM ORDER QUANTITY");

        jLabel18.setText("PRICE");

        jLabel19.setText("MINIMUM QUANTITY");

        javax.swing.GroupLayout additempageLayout = new javax.swing.GroupLayout(additempage);
        additempage.setLayout(additempageLayout);
        additempageLayout.setHorizontalGroup(
            additempageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, additempageLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(additempageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(additempageLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addComponent(MOQSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, additempageLayout.createSequentialGroup()
                        .addGroup(additempageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addGroup(additempageLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(CreateNewItemButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(additempageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PRICETextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SUPPLIERTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ITEMNAMETextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, additempageLayout.createSequentialGroup()
                                .addComponent(jToggleButton3)
                                .addGap(31, 31, 31))
                            .addComponent(ITEMCODETextField, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, additempageLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MINIMUMSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70))
        );
        additempageLayout.setVerticalGroup(
            additempageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(additempageLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(additempageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ITEMCODETextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(additempageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ITEMNAMETextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(additempageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SUPPLIERTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(additempageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MOQSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(additempageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PRICETextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(additempageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MINIMUMSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(additempageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateNewItemButton)
                    .addComponent(jToggleButton3))
                .addGap(36, 36, 36))
        );

        Parent.add(additempage, "card7");

        removeqtyremoveoptionspagebutton.setText("REMOVE QUANTITY");
        removeqtyremoveoptionspagebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeqtyremoveoptionspagebuttonActionPerformed(evt);
            }
        });

        removeitemremoveoptionspagebutton.setText("REMOVE ITEM");
        removeitemremoveoptionspagebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeitemremoveoptionspagebuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout removeoptionspageLayout = new javax.swing.GroupLayout(removeoptionspage);
        removeoptionspage.setLayout(removeoptionspageLayout);
        removeoptionspageLayout.setHorizontalGroup(
            removeoptionspageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeoptionspageLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(removeqtyremoveoptionspagebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(removeitemremoveoptionspagebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        removeoptionspageLayout.setVerticalGroup(
            removeoptionspageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeoptionspageLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(removeoptionspageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(removeqtyremoveoptionspagebutton, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(removeitemremoveoptionspagebutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        Parent.add(removeoptionspage, "card8");

        jLabel20.setText("ITEM CODE");

        jLabel21.setText("QUANTITY");

        jTextField9.setText("jTextField4");

        jToggleButton4.setText("REMOVE QUANTITY");

        javax.swing.GroupLayout removeqtypageLayout = new javax.swing.GroupLayout(removeqtypage);
        removeqtypage.setLayout(removeqtypageLayout);
        removeqtypageLayout.setHorizontalGroup(
            removeqtypageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeqtypageLayout.createSequentialGroup()
                .addGroup(removeqtypageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(removeqtypageLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(removeqtypageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(removeqtypageLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(37, 37, 37)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel21)
                                .addGap(34, 34, 34)
                                .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(list3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(removeqtypageLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jToggleButton4)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        removeqtypageLayout.setVerticalGroup(
            removeqtypageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, removeqtypageLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(list3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(removeqtypageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jToggleButton4)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        Parent.add(removeqtypage, "card9");

        jLabel22.setText("ITEM CODE");

        jTextField10.setText("jTextField4");

        jToggleButton5.setText("REMOVE QUANTITY");

        javax.swing.GroupLayout removeitempageLayout = new javax.swing.GroupLayout(removeitempage);
        removeitempage.setLayout(removeitempageLayout);
        removeitempageLayout.setHorizontalGroup(
            removeitempageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeitempageLayout.createSequentialGroup()
                .addGroup(removeitempageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(removeitempageLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(list4, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(removeitempageLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel22)
                        .addGap(137, 137, 137)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(removeitempageLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jToggleButton5)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        removeitempageLayout.setVerticalGroup(
            removeitempageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeitempageLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(list4, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(removeitempageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jToggleButton5)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        Parent.add(removeitempage, "card10");

        jToggleButton6.setText("GENERATE INVENTORY STATUS DOCUMENT");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jTextField11.setText("jTextField11");

        jTextField12.setText("jTextField12");

        jTextField13.setText("jTextField13");

        jTextField14.setText("jTextField14");

        jLabel23.setText("TOTAL ITEMS");

        jLabel24.setText("TOTAL QUANTITY");

        jLabel25.setText("ITEMS BELOW MINIMUM STOCK");

        jLabel26.setText("ITEMS OUT OF STOCK");

        javax.swing.GroupLayout inventorypageLayout = new javax.swing.GroupLayout(inventorypage);
        inventorypage.setLayout(inventorypageLayout);
        inventorypageLayout.setHorizontalGroup(
            inventorypageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventorypageLayout.createSequentialGroup()
                .addGroup(inventorypageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(inventorypageLayout.createSequentialGroup()
                        .addGroup(inventorypageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(inventorypageLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(list5, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(inventorypageLayout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jToggleButton6)))
                        .addGap(6, 6, 6))
                    .addGroup(inventorypageLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(inventorypageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel23)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(inventorypageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        inventorypageLayout.setVerticalGroup(
            inventorypageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventorypageLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(inventorypageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(inventorypageLayout.createSequentialGroup()
                        .addGroup(inventorypageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(inventorypageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(inventorypageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(inventorypageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(list5, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jToggleButton6)
                .addGap(31, 31, 31))
        );

        Parent.add(inventorypage, "card11");

        jToggleButton7.setText("GENERATE ORDER REQUEST DOCUMENT");

        javax.swing.GroupLayout orderpageLayout = new javax.swing.GroupLayout(orderpage);
        orderpage.setLayout(orderpageLayout);
        orderpageLayout.setHorizontalGroup(
            orderpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderpageLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(list6, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderpageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton7)
                .addGap(103, 103, 103))
        );
        orderpageLayout.setVerticalGroup(
            orderpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderpageLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(list6, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jToggleButton7)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        Parent.add(orderpage, "card12");

        getContentPane().add(Parent);
        Parent.setBounds(160, 0, 480, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //=============================Login/Registration Panel==============================
    //this is the registration button used to change panels tot he regsitration page.
    private void registersidepanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registersidepanelbuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(Registrationsidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(registrationpage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_registersidepanelbuttonActionPerformed

    private void loginsidepanelbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginsidepanelbutton1ActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(Loginsidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(Loginpage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_loginsidepanelbutton1ActionPerformed

    private void LogouthomesidepanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogouthomesidepanelbuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(Loginsidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(Loginpage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_LogouthomesidepanelbuttonActionPerformed

    private void homeoptionssidepanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeoptionssidepanelbuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(Homesidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(homepage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_homeoptionssidepanelbuttonActionPerformed

    private void additemoptionssidepanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additemoptionssidepanelbuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(optionssidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(addoptionspage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_additemoptionssidepanelbuttonActionPerformed

    private void removeitemoptionssidepanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeitemoptionssidepanelbuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(optionssidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(removeoptionspage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_removeitemoptionssidepanelbuttonActionPerformed

    private void inventoryoptionssidepanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryoptionssidepanelbuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(inventorysidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(inventorypage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_inventoryoptionssidepanelbuttonActionPerformed

    private void orderrequestoptionssidepanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderrequestoptionssidepanelbuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(ordersidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(orderpage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_orderrequestoptionssidepanelbuttonActionPerformed

    private void LogoutoptionssidepanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutoptionssidepanelbuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(Loginsidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(Loginpage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_LogoutoptionssidepanelbuttonActionPerformed

    private void homeinventorysidepanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeinventorysidepanelbuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(Homesidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(homepage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_homeinventorysidepanelbuttonActionPerformed

    private void additeminventorysidepanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additeminventorysidepanelbuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(optionssidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(addoptionspage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_additeminventorysidepanelbuttonActionPerformed

    private void removeiteminventorysidepanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeiteminventorysidepanelbuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(optionssidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(removeoptionspage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_removeiteminventorysidepanelbuttonActionPerformed

    private void orderrequestinventorysidepanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderrequestinventorysidepanelbuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(ordersidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(orderpage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_orderrequestinventorysidepanelbuttonActionPerformed

    private void Logoutinventorysidepanelbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logoutinventorysidepanelbutton1ActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(Loginsidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(Loginpage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_Logoutinventorysidepanelbutton1ActionPerformed

    private void homeordersidepanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeordersidepanelbuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(Homesidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(homepage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_homeordersidepanelbuttonActionPerformed

    private void additemordersidepanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additemordersidepanelbuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(optionssidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(addoptionspage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_additemordersidepanelbuttonActionPerformed

    private void removeitemordersidepanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeitemordersidepanelbuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(optionssidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(removeoptionspage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_removeitemordersidepanelbuttonActionPerformed

    private void inventoryordersidepanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryordersidepanelbuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(inventorysidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(inventorypage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_inventoryordersidepanelbuttonActionPerformed

    private void LogoutordersidepanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutordersidepanelbuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(Loginsidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(Loginpage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_LogoutordersidepanelbuttonActionPerformed

    private void loginloginpagebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginloginpagebuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(Homesidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(homepage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_loginloginpagebuttonActionPerformed

    private void RegisterSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterSaveButtonActionPerformed
        // TODO add your handling code here:
        try {
            String name = RegisterNameTextField.getText();
            String uid = RegisterUIDTextField.getText();
            String password = new String(RegisterPasswordField.getPassword());
            String confirmPassword = new String(RegisterPasswordConfirmField.getPassword());
            if (!confirmPassword.equals(password)) {
                throw new Exception("Password does not match.");
            }
            userMap.put(uid, new Security(name, uid, password));
            InventoryDBManager i = new InventoryDBManager();
            i.UpdateSecurityTable(userMap);

            RegisterNameTextField.setText("");
            RegisterUIDTextField.setText("");
            RegisterPasswordField.setText("");
            RegisterPasswordConfirmField.setText("");

            JOptionPane.showMessageDialog(this, "User registered successfully!");

            //switches back to the login panel.
            sidepanel.removeAll();
            sidepanel.add(Loginsidepanel);
            sidepanel.repaint();
            sidepanel.revalidate();

            Parent.removeAll();
            Parent.add(Loginpage);
            Parent.repaint();
            Parent.revalidate();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Registration Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_RegisterSaveButtonActionPerformed

    private void additemhomepagebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additemhomepagebuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(optionssidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(addoptionspage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_additemhomepagebuttonActionPerformed

    private void removeitemhomepagebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeitemhomepagebuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(optionssidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(removeoptionspage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_removeitemhomepagebuttonActionPerformed

    private void inventorystatushomepagebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventorystatushomepagebuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(inventorysidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(inventorypage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_inventorystatushomepagebuttonActionPerformed

    private void orderrequesthomepagebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderrequesthomepagebuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(ordersidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(orderpage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_orderrequesthomepagebuttonActionPerformed

    private void addqtyaddoptionspageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addqtyaddoptionspageActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(optionssidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(addqtypage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_addqtyaddoptionspageActionPerformed

    private void additemaddoptionspageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additemaddoptionspageActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(optionssidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(additempage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_additemaddoptionspageActionPerformed

    private void removeqtyremoveoptionspagebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeqtyremoveoptionspagebuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(optionssidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(removeqtypage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_removeqtyremoveoptionspagebuttonActionPerformed

    private void removeitemremoveoptionspagebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeitemremoveoptionspagebuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(optionssidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(removeitempage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_removeitemremoveoptionspagebuttonActionPerformed
    //Create new Item Page, and Item is saved to database when added
    private void CreateNewItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateNewItemButtonActionPerformed
        String code = ITEMCODETextField.getText();
        String name = ITEMNAMETextField.getText();
        String supplier = SUPPLIERTextField.getText();
        Integer moq = (Integer)MOQSpinner.getValue();
        Double price = Double.parseDouble(PRICETextField.getText()); // needs to be converted to a double
        Integer min = (Integer)MINIMUMSpinner.getValue();
        
        //Item(String itemCode, String itemName, int qty, int moq, int stkMin, double price)
        inventoryMap.put(code, new Item(code,name,1, moq, min, price));
        InventoryDBManager i = new InventoryDBManager();
        i.UpdateInventoryTable(inventoryMap);
        
        JOptionPane.showMessageDialog(this, "Item Registered Successfully!");
    }//GEN-LAST:event_CreateNewItemButtonActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(maingui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(maingui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(maingui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(maingui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new maingui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton CreateNewItemButton;
    private javax.swing.JPanel Homesidepanel;
    private javax.swing.JTextField ITEMCODETextField;
    private javax.swing.JTextField ITEMNAMETextField;
    private javax.swing.JPanel Loginpage;
    private javax.swing.JPanel Loginsidepanel;
    private javax.swing.JToggleButton Logouthomesidepanelbutton;
    private javax.swing.JToggleButton Logoutinventorysidepanelbutton1;
    private javax.swing.JToggleButton Logoutoptionssidepanelbutton;
    private javax.swing.JToggleButton Logoutordersidepanelbutton;
    private javax.swing.JSpinner MINIMUMSpinner;
    private javax.swing.JSpinner MOQSpinner;
    private javax.swing.JTextField PRICETextField;
    private javax.swing.JPanel Parent;
    private javax.swing.JTextField RegisterNameTextField;
    private javax.swing.JPasswordField RegisterPasswordConfirmField;
    private javax.swing.JPasswordField RegisterPasswordField;
    private javax.swing.JToggleButton RegisterSaveButton;
    private javax.swing.JTextField RegisterUIDTextField;
    private javax.swing.JPanel Registrationsidepanel;
    private javax.swing.JTextField SUPPLIERTextField;
    private javax.swing.JToggleButton additemaddoptionspage;
    private javax.swing.JToggleButton additemhomepagebutton;
    private javax.swing.JToggleButton additeminventorysidepanelbutton;
    private javax.swing.JToggleButton additemoptionssidepanelbutton;
    private javax.swing.JToggleButton additemordersidepanelbutton;
    private javax.swing.JPanel additempage;
    private javax.swing.JPanel addoptionspage;
    private javax.swing.JToggleButton addqtyaddoptionspage;
    private javax.swing.JPanel addqtypage;
    private javax.swing.JToggleButton homeinventorysidepanelbutton;
    private javax.swing.JToggleButton homeoptionssidepanelbutton;
    private javax.swing.JToggleButton homeordersidepanelbutton;
    private javax.swing.JPanel homepage;
    private javax.swing.JToggleButton inventoryoptionssidepanelbutton;
    private javax.swing.JToggleButton inventoryordersidepanelbutton;
    private javax.swing.JPanel inventorypage;
    private javax.swing.JPanel inventorysidepanel;
    private javax.swing.JToggleButton inventorystatushomepagebutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private java.awt.List list1;
    private java.awt.List list2;
    private java.awt.List list3;
    private java.awt.List list4;
    private java.awt.List list5;
    private java.awt.List list6;
    private javax.swing.JToggleButton loginloginpagebutton;
    private javax.swing.JToggleButton loginsidepanelbutton1;
    private javax.swing.JPanel optionssidepanel;
    private javax.swing.JPanel orderpage;
    private javax.swing.JToggleButton orderrequesthomepagebutton;
    private javax.swing.JToggleButton orderrequestinventorysidepanelbutton;
    private javax.swing.JToggleButton orderrequestoptionssidepanelbutton;
    private javax.swing.JPanel ordersidepanel;
    private java.awt.Panel panel1;
    private javax.swing.JToggleButton registersidepanelbutton;
    private javax.swing.JPanel registrationpage;
    private javax.swing.JToggleButton removeitemhomepagebutton;
    private javax.swing.JToggleButton removeiteminventorysidepanelbutton;
    private javax.swing.JToggleButton removeitemoptionssidepanelbutton;
    private javax.swing.JToggleButton removeitemordersidepanelbutton;
    private javax.swing.JPanel removeitempage;
    private javax.swing.JToggleButton removeitemremoveoptionspagebutton;
    private javax.swing.JPanel removeoptionspage;
    private javax.swing.JPanel removeqtypage;
    private javax.swing.JToggleButton removeqtyremoveoptionspagebutton;
    private javax.swing.JPanel sidepanel;
    // End of variables declaration//GEN-END:variables
}
