
import inventory.system.InventoryDBManager;
import inventory.system.InventorySystem;
import inventory.system.Item;
import inventory.system.Security;
import java.util.Map;
import javax.swing.JOptionPane;

public class maingui extends javax.swing.JFrame {

    private Map<String, Security> userMap = InventorySystem.getSecurityMap();
    private Map<String, Item> inventoryMap = InventorySystem.getHashMap();

    public maingui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        list2 = new java.awt.List();
        sidepanel = new javax.swing.JPanel();
        Loginsidepanel = new javax.swing.JPanel();
        registersidepanelbutton = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Registrationsidepanel = new javax.swing.JPanel();
        loginsidepanelbutton1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Homesidepanel = new javax.swing.JPanel();
        Logouthomesidepanelbutton = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        optionssidepanel = new javax.swing.JPanel();
        Logoutoptionssidepanelbutton = new javax.swing.JToggleButton();
        additemoptionssidepanelbutton = new javax.swing.JToggleButton();
        removeitemoptionssidepanelbutton = new javax.swing.JToggleButton();
        inventoryoptionssidepanelbutton = new javax.swing.JToggleButton();
        orderrequestoptionssidepanelbutton = new javax.swing.JToggleButton();
        homeoptionssidepanelbutton = new javax.swing.JToggleButton();
        inventorysidepanel = new javax.swing.JPanel();
        additeminventorysidepanelbutton = new javax.swing.JToggleButton();
        removeiteminventorysidepanelbutton = new javax.swing.JToggleButton();
        orderrequestinventorysidepanelbutton = new javax.swing.JToggleButton();
        Logoutinventorysidepanelbutton1 = new javax.swing.JToggleButton();
        homeinventorysidepanelbutton = new javax.swing.JToggleButton();
        ordersidepanel = new javax.swing.JPanel();
        homeordersidepanelbutton = new javax.swing.JToggleButton();
        Logoutordersidepanelbutton = new javax.swing.JToggleButton();
        additemordersidepanelbutton = new javax.swing.JToggleButton();
        removeitemordersidepanelbutton = new javax.swing.JToggleButton();
        inventoryordersidepanelbutton = new javax.swing.JToggleButton();
        Parent = new javax.swing.JPanel();
        Loginpage = new javax.swing.JPanel();
        LOGINUSERIDTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        LOGINPASSWORDJPasswordField = new javax.swing.JPasswordField();
        loginloginpagebutton = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        registrationpage = new javax.swing.JPanel();
        RegisterNameTextField = new javax.swing.JTextField();
        RegisterUIDTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        RegisterPasswordField = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        RegisterPasswordConfirmField = new javax.swing.JPasswordField();
        registerregistrationpagebutton = new javax.swing.JToggleButton();
        homepage = new javax.swing.JPanel();
        removeitemhomepagebutton = new javax.swing.JToggleButton();
        inventorystatushomepagebutton = new javax.swing.JToggleButton();
        additemhomepagebutton = new javax.swing.JToggleButton();
        orderrequesthomepagebutton = new javax.swing.JToggleButton();
        jLabel27 = new javax.swing.JLabel();
        addoptionspage = new javax.swing.JPanel();
        addqtyaddoptionspage = new javax.swing.JToggleButton();
        additemaddoptionspage = new javax.swing.JToggleButton();
        jLabel28 = new javax.swing.JLabel();
        addqtypage = new javax.swing.JPanel();
        ITEMLISTField = new java.awt.List();
        ITEMQTYSpinner = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ITEMADDQTYButton = new javax.swing.JToggleButton();
        ITEMCODEBox = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        additempage = new javax.swing.JPanel();
        ITEMCODETextField = new javax.swing.JTextField();
        ITEMNAMETextField = new javax.swing.JTextField();
        SUPPLIERTextField = new javax.swing.JTextField();
        MOQSpinner = new javax.swing.JSpinner();
        PRICETextField = new javax.swing.JTextField();
        MINIMUMSpinner = new javax.swing.JSpinner();
        CREATENEWITEMButton = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        removeoptionspage = new javax.swing.JPanel();
        removeqtyremoveoptionspagebutton = new javax.swing.JToggleButton();
        removeitemremoveoptionspagebutton = new javax.swing.JToggleButton();
        jLabel29 = new javax.swing.JLabel();
        removeqtypage = new javax.swing.JPanel();
        REMOVEITEMQTYSpinner = new javax.swing.JSpinner();
        REMOVEITEMList = new java.awt.List();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        REMOVEQTYButton = new javax.swing.JToggleButton();
        REMOVEITEMQTYBox = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        removeitempage = new javax.swing.JPanel();
        list4 = new java.awt.List();
        jLabel22 = new javax.swing.JLabel();
        jToggleButton5 = new javax.swing.JToggleButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        inventorypage = new javax.swing.JPanel();
        list5 = new java.awt.List();
        jToggleButton6 = new javax.swing.JToggleButton();
        panel1 = new java.awt.Panel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        orderpage = new javax.swing.JPanel();
        ORDERREQUESTList = new java.awt.List();
        jToggleButton7 = new javax.swing.JToggleButton();
        jLabel31 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(640, 480));
        getContentPane().setLayout(null);

        sidepanel.setLayout(new java.awt.CardLayout());

        Loginsidepanel.setBackground(new java.awt.Color(102, 255, 255));

        registersidepanelbutton.setText("Register");
        registersidepanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registersidepanelbuttonActionPerformed(evt);
            }
        });

        jLabel1.setText("NEW USER?");

        jLabel2.setText("CLICK REGISTER TO SIGN UP");

        javax.swing.GroupLayout LoginsidepanelLayout = new javax.swing.GroupLayout(Loginsidepanel);
        Loginsidepanel.setLayout(LoginsidepanelLayout);
        LoginsidepanelLayout.setHorizontalGroup(
            LoginsidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginsidepanelLayout.createSequentialGroup()
                .addGroup(LoginsidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginsidepanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(LoginsidepanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1))
                    .addGroup(LoginsidepanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(registersidepanelbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LoginsidepanelLayout.setVerticalGroup(
            LoginsidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginsidepanelLayout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(registersidepanelbutton)
                .addGap(190, 190, 190))
        );

        sidepanel.add(Loginsidepanel, "card2");

        Registrationsidepanel.setBackground(new java.awt.Color(102, 255, 255));

        loginsidepanelbutton1.setBackground(new java.awt.Color(102, 255, 102));
        loginsidepanelbutton1.setText("Login");
        loginsidepanelbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginsidepanelbutton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("ALREADY REGISTERED");

        jLabel4.setText("Click on login");

        javax.swing.GroupLayout RegistrationsidepanelLayout = new javax.swing.GroupLayout(Registrationsidepanel);
        Registrationsidepanel.setLayout(RegistrationsidepanelLayout);
        RegistrationsidepanelLayout.setHorizontalGroup(
            RegistrationsidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrationsidepanelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18))
            .addGroup(RegistrationsidepanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(RegistrationsidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RegistrationsidepanelLayout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(loginsidepanelbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );
        RegistrationsidepanelLayout.setVerticalGroup(
            RegistrationsidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrationsidepanelLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(230, Short.MAX_VALUE))
            .addGroup(RegistrationsidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RegistrationsidepanelLayout.createSequentialGroup()
                    .addGap(188, 188, 188)
                    .addComponent(loginsidepanelbutton1)
                    .addContainerGap(189, Short.MAX_VALUE)))
        );

        sidepanel.add(Registrationsidepanel, "card3");

        Homesidepanel.setBackground(new java.awt.Color(255, 255, 255));

        Logouthomesidepanelbutton.setBackground(new java.awt.Color(255, 51, 51));
        Logouthomesidepanelbutton.setForeground(new java.awt.Color(255, 255, 255));
        Logouthomesidepanelbutton.setText("LOG OUT");
        Logouthomesidepanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogouthomesidepanelbuttonActionPerformed(evt);
            }
        });

        jLabel5.setText("WELCOME BACK!!");

        javax.swing.GroupLayout HomesidepanelLayout = new javax.swing.GroupLayout(Homesidepanel);
        Homesidepanel.setLayout(HomesidepanelLayout);
        HomesidepanelLayout.setHorizontalGroup(
            HomesidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomesidepanelLayout.createSequentialGroup()
                .addGroup(HomesidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomesidepanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(Logouthomesidepanelbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HomesidepanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        HomesidepanelLayout.setVerticalGroup(
            HomesidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomesidepanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, Short.MAX_VALUE)
                .addComponent(Logouthomesidepanelbutton)
                .addGap(15, 15, 15))
        );

        sidepanel.add(Homesidepanel, "card4");

        Logoutoptionssidepanelbutton.setBackground(new java.awt.Color(255, 51, 51));
        Logoutoptionssidepanelbutton.setForeground(new java.awt.Color(255, 255, 255));
        Logoutoptionssidepanelbutton.setText("LOG OUT");
        Logoutoptionssidepanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutoptionssidepanelbuttonActionPerformed(evt);
            }
        });

        additemoptionssidepanelbutton.setText("ADD ITEM");
        additemoptionssidepanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additemoptionssidepanelbuttonActionPerformed(evt);
            }
        });

        removeitemoptionssidepanelbutton.setText("REMOVE ITEM");
        removeitemoptionssidepanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeitemoptionssidepanelbuttonActionPerformed(evt);
            }
        });

        inventoryoptionssidepanelbutton.setText("INVENTORY STATUS");
        inventoryoptionssidepanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryoptionssidepanelbuttonActionPerformed(evt);
            }
        });

        orderrequestoptionssidepanelbutton.setText("ORDER REQUEST");
        orderrequestoptionssidepanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderrequestoptionssidepanelbuttonActionPerformed(evt);
            }
        });

        homeoptionssidepanelbutton.setText("HOME");
        homeoptionssidepanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeoptionssidepanelbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionssidepanelLayout = new javax.swing.GroupLayout(optionssidepanel);
        optionssidepanel.setLayout(optionssidepanelLayout);
        optionssidepanelLayout.setHorizontalGroup(
            optionssidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionssidepanelLayout.createSequentialGroup()
                .addGroup(optionssidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionssidepanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(optionssidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inventoryoptionssidepanelbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(orderrequestoptionssidepanelbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removeitemoptionssidepanelbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(additemoptionssidepanelbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(optionssidepanelLayout.createSequentialGroup()
                        .addGroup(optionssidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(optionssidepanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(Logoutoptionssidepanelbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(optionssidepanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(homeoptionssidepanelbutton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        optionssidepanelLayout.setVerticalGroup(
            optionssidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionssidepanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(homeoptionssidepanelbutton)
                .addGap(66, 66, 66)
                .addComponent(additemoptionssidepanelbutton)
                .addGap(18, 18, 18)
                .addComponent(removeitemoptionssidepanelbutton)
                .addGap(18, 18, 18)
                .addComponent(inventoryoptionssidepanelbutton)
                .addGap(18, 18, 18)
                .addComponent(orderrequestoptionssidepanelbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(Logoutoptionssidepanelbutton)
                .addGap(23, 23, 23))
        );

        sidepanel.add(optionssidepanel, "card5");

        additeminventorysidepanelbutton.setText("ADD ITEM");
        additeminventorysidepanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additeminventorysidepanelbuttonActionPerformed(evt);
            }
        });

        removeiteminventorysidepanelbutton.setText("REMOVE ITEM");
        removeiteminventorysidepanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeiteminventorysidepanelbuttonActionPerformed(evt);
            }
        });

        orderrequestinventorysidepanelbutton.setText("ORDER REQUEST");
        orderrequestinventorysidepanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderrequestinventorysidepanelbuttonActionPerformed(evt);
            }
        });

        Logoutinventorysidepanelbutton1.setBackground(new java.awt.Color(255, 51, 51));
        Logoutinventorysidepanelbutton1.setForeground(new java.awt.Color(255, 255, 255));
        Logoutinventorysidepanelbutton1.setText("LOG OUT");
        Logoutinventorysidepanelbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logoutinventorysidepanelbutton1ActionPerformed(evt);
            }
        });

        homeinventorysidepanelbutton.setText("HOME");
        homeinventorysidepanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeinventorysidepanelbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inventorysidepanelLayout = new javax.swing.GroupLayout(inventorysidepanel);
        inventorysidepanel.setLayout(inventorysidepanelLayout);
        inventorysidepanelLayout.setHorizontalGroup(
            inventorysidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventorysidepanelLayout.createSequentialGroup()
                .addGroup(inventorysidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inventorysidepanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(inventorysidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(additeminventorysidepanelbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(removeiteminventorysidepanelbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(orderrequestinventorysidepanelbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(inventorysidepanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(Logoutinventorysidepanelbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(inventorysidepanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(homeinventorysidepanelbutton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inventorysidepanelLayout.setVerticalGroup(
            inventorysidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventorysidepanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(homeinventorysidepanelbutton)
                .addGap(88, 88, 88)
                .addComponent(additeminventorysidepanelbutton)
                .addGap(18, 18, 18)
                .addComponent(removeiteminventorysidepanelbutton)
                .addGap(18, 18, 18)
                .addComponent(orderrequestinventorysidepanelbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(Logoutinventorysidepanelbutton1)
                .addGap(21, 21, 21))
        );

        sidepanel.add(inventorysidepanel, "card6");

        homeordersidepanelbutton.setText("HOME");
        homeordersidepanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeordersidepanelbuttonActionPerformed(evt);
            }
        });

        Logoutordersidepanelbutton.setBackground(new java.awt.Color(255, 51, 51));
        Logoutordersidepanelbutton.setForeground(new java.awt.Color(255, 255, 255));
        Logoutordersidepanelbutton.setText("LOG OUT");
        Logoutordersidepanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutordersidepanelbuttonActionPerformed(evt);
            }
        });

        additemordersidepanelbutton.setText("ADD ITEM");
        additemordersidepanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additemordersidepanelbuttonActionPerformed(evt);
            }
        });

        removeitemordersidepanelbutton.setText("REMOVE ITEM");
        removeitemordersidepanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeitemordersidepanelbuttonActionPerformed(evt);
            }
        });

        inventoryordersidepanelbutton.setText("INVENTORY STATUS");
        inventoryordersidepanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryordersidepanelbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ordersidepanelLayout = new javax.swing.GroupLayout(ordersidepanel);
        ordersidepanel.setLayout(ordersidepanelLayout);
        ordersidepanelLayout.setHorizontalGroup(
            ordersidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ordersidepanelLayout.createSequentialGroup()
                .addGroup(ordersidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ordersidepanelLayout.createSequentialGroup()
                        .addGroup(ordersidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ordersidepanelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(homeordersidepanelbutton))
                            .addGroup(ordersidepanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(Logoutordersidepanelbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ordersidepanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ordersidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inventoryordersidepanelbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(removeitemordersidepanelbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(additemordersidepanelbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        ordersidepanelLayout.setVerticalGroup(
            ordersidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordersidepanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(homeordersidepanelbutton)
                .addGap(71, 71, 71)
                .addComponent(additemordersidepanelbutton)
                .addGap(18, 18, 18)
                .addComponent(removeitemordersidepanelbutton)
                .addGap(18, 18, 18)
                .addComponent(inventoryordersidepanelbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(Logoutordersidepanelbutton)
                .addGap(31, 31, 31))
        );

        sidepanel.add(ordersidepanel, "card7");

        getContentPane().add(sidepanel);
        sidepanel.setBounds(0, 0, 160, 400);

        Parent.setLayout(new java.awt.CardLayout());

        LOGINUSERIDTextField.setText("jTextField1");

        jLabel6.setText("USER ID");

        LOGINPASSWORDJPasswordField.setText("jPasswordField1");

        loginloginpagebutton.setBackground(new java.awt.Color(102, 255, 102));
        loginloginpagebutton.setText("Login");
        loginloginpagebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginloginpagebuttonActionPerformed(evt);
            }
        });

        jLabel7.setText("PASSWORD");

        javax.swing.GroupLayout LoginpageLayout = new javax.swing.GroupLayout(Loginpage);
        Loginpage.setLayout(LoginpageLayout);
        LoginpageLayout.setHorizontalGroup(
            LoginpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginpageLayout.createSequentialGroup()
                .addGroup(LoginpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginpageLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel6))
                    .addGroup(LoginpageLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(LoginpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LOGINUSERIDTextField)
                            .addComponent(LOGINPASSWORDJPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)))
                    .addGroup(LoginpageLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(loginloginpagebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginpageLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel7)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        LoginpageLayout.setVerticalGroup(
            LoginpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginpageLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LOGINUSERIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LOGINPASSWORDJPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginloginpagebutton)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        Parent.add(Loginpage, "card2");

        RegisterNameTextField.setText("jTextField2");

        RegisterUIDTextField.setText("jTextField3");

        jLabel8.setText("NAME");

        jLabel9.setText("USER ID");

        jLabel10.setText("PASSWORD");

        RegisterPasswordField.setText("jPasswordField2");

        jLabel11.setText("RE-TYPE PASSWORD");

        RegisterPasswordConfirmField.setText("jPasswordField3");

        registerregistrationpagebutton.setText("Register");
        registerregistrationpagebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerregistrationpagebuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registrationpageLayout = new javax.swing.GroupLayout(registrationpage);
        registrationpage.setLayout(registrationpageLayout);
        registrationpageLayout.setHorizontalGroup(
            registrationpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrationpageLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(registrationpageLayout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(registrationpageLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(registrationpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RegisterNameTextField)
                    .addComponent(RegisterUIDTextField)
                    .addComponent(RegisterPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(RegisterPasswordConfirmField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrationpageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registerregistrationpagebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrationpageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(205, 205, 205))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrationpageLayout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(183, 183, 183))
        );
        registrationpageLayout.setVerticalGroup(
            registrationpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrationpageLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RegisterNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RegisterUIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RegisterPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RegisterPasswordConfirmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(registerregistrationpagebutton)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        Parent.add(registrationpage, "card3");

        homepage.setLayout(null);

        removeitemhomepagebutton.setText("REMOVE ITEM");
        removeitemhomepagebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeitemhomepagebuttonActionPerformed(evt);
            }
        });
        homepage.add(removeitemhomepagebutton);
        removeitemhomepagebutton.setBounds(258, 58, 177, 125);

        inventorystatushomepagebutton.setText("INVENTORY STATUS");
        inventorystatushomepagebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventorystatushomepagebuttonActionPerformed(evt);
            }
        });
        homepage.add(inventorystatushomepagebutton);
        inventorystatushomepagebutton.setBounds(53, 209, 177, 125);

        additemhomepagebutton.setText("ADD ITEM");
        additemhomepagebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additemhomepagebuttonActionPerformed(evt);
            }
        });
        homepage.add(additemhomepagebutton);
        additemhomepagebutton.setBounds(53, 58, 177, 125);

        orderrequesthomepagebutton.setText("ORDER REQUEST");
        orderrequesthomepagebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderrequesthomepagebuttonActionPerformed(evt);
            }
        });
        homepage.add(orderrequesthomepagebutton);
        orderrequesthomepagebutton.setBounds(258, 209, 177, 125);
        homepage.add(jLabel27);
        jLabel27.setBounds(0, 0, 480, 400);

        Parent.add(homepage, "card4");

        addoptionspage.setLayout(null);

        addqtyaddoptionspage.setText("ADD QUANTITY");
        addqtyaddoptionspage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addqtyaddoptionspageActionPerformed(evt);
            }
        });
        addoptionspage.add(addqtyaddoptionspage);
        addqtyaddoptionspage.setBounds(60, 141, 170, 110);

        additemaddoptionspage.setText("ADD NEW ITEM");
        additemaddoptionspage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additemaddoptionspageActionPerformed(evt);
            }
        });
        addoptionspage.add(additemaddoptionspage);
        additemaddoptionspage.setBounds(248, 141, 170, 110);
        addoptionspage.add(jLabel28);
        jLabel28.setBounds(0, 0, 480, 400);

        Parent.add(addoptionspage, "card5");

        addqtypage.setLayout(null);
        addqtypage.add(ITEMLISTField);
        ITEMLISTField.setBounds(39, 50, 400, 239);
        addqtypage.add(ITEMQTYSpinner);
        ITEMQTYSpinner.setBounds(350, 310, 64, 22);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ITEM CODE");
        addqtypage.add(jLabel12);
        jLabel12.setBounds(40, 310, 65, 16);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("QUANTITY");
        addqtypage.add(jLabel13);
        jLabel13.setBounds(270, 310, 80, 16);

        ITEMADDQTYButton.setText("ADD QUANTITY");
        ITEMADDQTYButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ITEMADDQTYButtonActionPerformed(evt);
            }
        });
        addqtypage.add(ITEMADDQTYButton);
        ITEMADDQTYButton.setBounds(154, 350, 115, 23);

        ITEMCODEBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        addqtypage.add(ITEMCODEBox);
        ITEMCODEBox.setBounds(120, 310, 88, 22);
        addqtypage.add(jLabel33);
        jLabel33.setBounds(0, 0, 480, 400);

        Parent.add(addqtypage, "card6");

        additempage.setLayout(null);
        additempage.add(ITEMCODETextField);
        ITEMCODETextField.setBounds(302, 56, 108, 22);
        additempage.add(ITEMNAMETextField);
        ITEMNAMETextField.setBounds(302, 90, 108, 22);
        additempage.add(SUPPLIERTextField);
        SUPPLIERTextField.setBounds(302, 130, 108, 22);
        additempage.add(MOQSpinner);
        MOQSpinner.setBounds(346, 170, 64, 22);

        PRICETextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        PRICETextField.setText("0.00");
        additempage.add(PRICETextField);
        PRICETextField.setBounds(302, 210, 108, 22);
        additempage.add(MINIMUMSpinner);
        MINIMUMSpinner.setBounds(346, 250, 64, 22);

        CREATENEWITEMButton.setText("CREATE");
        CREATENEWITEMButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CREATENEWITEMButtonActionPerformed(evt);
            }
        });
        additempage.add(CREATENEWITEMButton);
        CREATENEWITEMButton.setBounds(86, 341, 71, 23);

        jToggleButton3.setText("REFRESH");
        additempage.add(jToggleButton3);
        jToggleButton3.setBounds(302, 341, 78, 23);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ITEM CODE");
        additempage.add(jLabel14);
        jLabel14.setBounds(67, 59, 70, 16);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("ITEM NAME");
        additempage.add(jLabel15);
        jLabel15.setBounds(67, 93, 69, 16);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("SUPPLIER");
        additempage.add(jLabel16);
        jLabel16.setBounds(67, 133, 55, 16);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("MINIMUM ORDER QUANTITY");
        additempage.add(jLabel17);
        jLabel17.setBounds(67, 173, 169, 16);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("PRICE");
        additempage.add(jLabel18);
        jLabel18.setBounds(67, 213, 33, 16);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("MINIMUM QUANTITY");
        additempage.add(jLabel19);
        jLabel19.setBounds(67, 253, 125, 16);
        additempage.add(jLabel34);
        jLabel34.setBounds(0, 0, 480, 400);

        Parent.add(additempage, "card7");

        removeoptionspage.setLayout(null);

        removeqtyremoveoptionspagebutton.setText("REMOVE QUANTITY");
        removeqtyremoveoptionspagebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeqtyremoveoptionspagebuttonActionPerformed(evt);
            }
        });
        removeoptionspage.add(removeqtyremoveoptionspagebutton);
        removeqtyremoveoptionspagebutton.setBounds(67, 141, 170, 110);

        removeitemremoveoptionspagebutton.setText("REMOVE ITEM");
        removeitemremoveoptionspagebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeitemremoveoptionspagebuttonActionPerformed(evt);
            }
        });
        removeoptionspage.add(removeitemremoveoptionspagebutton);
        removeitemremoveoptionspagebutton.setBounds(255, 141, 170, 110);
        removeoptionspage.add(jLabel29);
        jLabel29.setBounds(0, 0, 480, 400);

        Parent.add(removeoptionspage, "card8");

        removeqtypage.setLayout(null);
        removeqtypage.add(REMOVEITEMQTYSpinner);
        REMOVEITEMQTYSpinner.setBounds(376, 305, 64, 22);
        removeqtypage.add(REMOVEITEMList);
        REMOVEITEMList.setBounds(40, 38, 400, 239);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("ITEM CODE");
        removeqtypage.add(jLabel20);
        jLabel20.setBounds(40, 308, 65, 16);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("QUANTITY");
        removeqtypage.add(jLabel21);
        jLabel21.setBounds(284, 308, 70, 16);

        REMOVEQTYButton.setText("REMOVE QUANTITY");
        REMOVEQTYButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REMOVEQTYButtonActionPerformed(evt);
            }
        });
        removeqtypage.add(REMOVEQTYButton);
        REMOVEQTYButton.setBounds(170, 345, 136, 23);

        REMOVEITEMQTYBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        removeqtypage.add(REMOVEITEMQTYBox);
        REMOVEITEMQTYBox.setBounds(119, 305, 95, 22);
        removeqtypage.add(jLabel35);
        jLabel35.setBounds(0, 0, 480, 400);

        Parent.add(removeqtypage, "card9");

        removeitempage.setLayout(null);
        removeitempage.add(list4);
        list4.setBounds(40, 38, 400, 239);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("ITEM CODE");
        removeitempage.add(jLabel22);
        jLabel22.setBounds(111, 303, 70, 16);

        jToggleButton5.setText("REMOVE ITEM");
        removeitempage.add(jToggleButton5);
        jToggleButton5.setBounds(152, 340, 106, 23);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        removeitempage.add(jComboBox2);
        jComboBox2.setBounds(218, 300, 120, 22);
        removeitempage.add(jLabel32);
        jLabel32.setBounds(0, 0, 480, 400);

        Parent.add(removeitempage, "card10");

        inventorypage.setLayout(null);
        inventorypage.add(list5);
        list5.setBounds(55, 142, 395, 183);

        jToggleButton6.setText("GENERATE INVENTORY STATUS DOCUMENT");
        inventorypage.add(jToggleButton6);
        jToggleButton6.setBounds(118, 346, 265, 23);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        inventorypage.add(panel1);
        panel1.setBounds(344, 20, 112, 112);

        jTextField11.setText("jTextField11");
        inventorypage.add(jTextField11);
        jTextField11.setBounds(244, 20, 77, 22);

        jTextField12.setText("jTextField12");
        inventorypage.add(jTextField12);
        jTextField12.setBounds(244, 48, 77, 22);

        jTextField13.setText("jTextField13");
        inventorypage.add(jTextField13);
        jTextField13.setBounds(244, 76, 77, 22);

        jTextField14.setText("jTextField14");
        inventorypage.add(jTextField14);
        jTextField14.setBounds(244, 104, 77, 22);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("TOTAL ITEMS");
        inventorypage.add(jLabel23);
        jLabel23.setBounds(31, 23, 90, 16);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("TOTAL QUANTITY");
        inventorypage.add(jLabel24);
        jLabel24.setBounds(31, 51, 104, 16);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("BELOW MINIMUM STOCK");
        inventorypage.add(jLabel25);
        jLabel25.setBounds(31, 79, 147, 16);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("OUT OF STOCK");
        inventorypage.add(jLabel26);
        jLabel26.setBounds(31, 107, 86, 16);
        inventorypage.add(jLabel30);
        jLabel30.setBounds(0, 0, 480, 400);

        Parent.add(inventorypage, "card11");

        orderpage.setLayout(null);
        orderpage.add(ORDERREQUESTList);
        ORDERREQUESTList.setBounds(45, 36, 386, 245);

        jToggleButton7.setText("GENERATE ORDER REQUEST DOCUMENT");
        orderpage.add(jToggleButton7);
        jToggleButton7.setBounds(129, 321, 249, 23);
        orderpage.add(jLabel31);
        jLabel31.setBounds(0, 0, 480, 400);

        Parent.add(orderpage, "card12");

        getContentPane().add(Parent);
        Parent.setBounds(160, 0, 480, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registersidepanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registersidepanelbuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(Registrationsidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(registrationpage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_registersidepanelbuttonActionPerformed

    private void loginsidepanelbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginsidepanelbutton1ActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(Loginsidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(Loginpage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_loginsidepanelbutton1ActionPerformed

    private void LogouthomesidepanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogouthomesidepanelbuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(Loginsidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(Loginpage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_LogouthomesidepanelbuttonActionPerformed

    private void homeoptionssidepanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeoptionssidepanelbuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(Homesidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(homepage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_homeoptionssidepanelbuttonActionPerformed

    private void additemoptionssidepanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additemoptionssidepanelbuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(optionssidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(addoptionspage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_additemoptionssidepanelbuttonActionPerformed

    private void removeitemoptionssidepanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeitemoptionssidepanelbuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(optionssidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(removeoptionspage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_removeitemoptionssidepanelbuttonActionPerformed

    private void inventoryoptionssidepanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryoptionssidepanelbuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(inventorysidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(inventorypage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_inventoryoptionssidepanelbuttonActionPerformed

    private void orderrequestoptionssidepanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderrequestoptionssidepanelbuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(ordersidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(orderpage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_orderrequestoptionssidepanelbuttonActionPerformed

    private void LogoutoptionssidepanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutoptionssidepanelbuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(Loginsidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(Loginpage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_LogoutoptionssidepanelbuttonActionPerformed

    private void homeinventorysidepanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeinventorysidepanelbuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(Homesidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(homepage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_homeinventorysidepanelbuttonActionPerformed

    private void additeminventorysidepanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additeminventorysidepanelbuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(optionssidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(addoptionspage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_additeminventorysidepanelbuttonActionPerformed

    private void removeiteminventorysidepanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeiteminventorysidepanelbuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(optionssidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(removeoptionspage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_removeiteminventorysidepanelbuttonActionPerformed

    private void orderrequestinventorysidepanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderrequestinventorysidepanelbuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(ordersidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(orderpage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_orderrequestinventorysidepanelbuttonActionPerformed

    private void Logoutinventorysidepanelbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logoutinventorysidepanelbutton1ActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(Loginsidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(Loginpage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_Logoutinventorysidepanelbutton1ActionPerformed

    private void homeordersidepanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeordersidepanelbuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(Homesidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(homepage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_homeordersidepanelbuttonActionPerformed

    private void additemordersidepanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additemordersidepanelbuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(optionssidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(addoptionspage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_additemordersidepanelbuttonActionPerformed

    private void removeitemordersidepanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeitemordersidepanelbuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(optionssidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(removeoptionspage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_removeitemordersidepanelbuttonActionPerformed

    private void inventoryordersidepanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryordersidepanelbuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(inventorysidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(inventorypage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_inventoryordersidepanelbuttonActionPerformed

    private void LogoutordersidepanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutordersidepanelbuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(Loginsidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(Loginpage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_LogoutordersidepanelbuttonActionPerformed

    private void loginloginpagebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginloginpagebuttonActionPerformed
        // TODO add your handling code here:
        InventoryDBManager i = new InventoryDBManager();
        userMap = i.LoadSecurityTable();

        String uid = LOGINUSERIDTextField.getText();
        String password = new String(LOGINPASSWORDJPasswordField.getPassword());
        int logincounter = 0;

        try {
            if (userMap.containsKey(uid)) {
                Security user = userMap.get(uid);
                if (user.getPassword().equals(password)) {
                    JOptionPane.showMessageDialog(this, "Login successful! Welcome " + user.getUserName());

                    sidepanel.removeAll();
                    sidepanel.add(Homesidepanel);
                    sidepanel.repaint();
                    sidepanel.revalidate();

                    Parent.removeAll();
                    Parent.add(homepage);
                    Parent.repaint();
                    Parent.revalidate();
                } else {
                    JOptionPane.showMessageDialog(this, "Incorrect password.", "Login Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "User ID not found.", "Login Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Registration Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_loginloginpagebuttonActionPerformed

    private void registerregistrationpagebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerregistrationpagebuttonActionPerformed
        // TODO add your handling code here:
        try {
            InventoryDBManager i = new InventoryDBManager();
            userMap = i.LoadSecurityTable(); //update hashmap with existing users
            String uid = RegisterUIDTextField.getText();
            if (userMap.containsKey(uid)) {
                throw new Exception("Current Username Already Exists!");
            }

            String name = RegisterNameTextField.getText();
            String password = new String(RegisterPasswordField.getPassword());
            String confirmPassword = new String(RegisterPasswordConfirmField.getPassword());
            if (!confirmPassword.equals(password)) {
                throw new Exception("Password does not match.");
            }
            userMap.put(uid, new Security(name, uid, password));
            i.UpdateSecurityTable(userMap);

            RegisterNameTextField.setText("");
            RegisterUIDTextField.setText("");
            RegisterPasswordField.setText("");
            RegisterPasswordConfirmField.setText("");

            JOptionPane.showMessageDialog(this, "User registered successfully!");

            //switches back to the login panel.
            sidepanel.removeAll();
            sidepanel.add(Loginsidepanel);
            sidepanel.repaint();
            sidepanel.revalidate();

            Parent.removeAll();
            Parent.add(Loginpage);
            Parent.repaint();
            Parent.revalidate();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Registration Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_registerregistrationpagebuttonActionPerformed

    private void additemhomepagebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additemhomepagebuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(optionssidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(addoptionspage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_additemhomepagebuttonActionPerformed

    private void removeitemhomepagebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeitemhomepagebuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(optionssidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(removeoptionspage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_removeitemhomepagebuttonActionPerformed

    private void inventorystatushomepagebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventorystatushomepagebuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(inventorysidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(inventorypage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_inventorystatushomepagebuttonActionPerformed

    private void orderrequesthomepagebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderrequesthomepagebuttonActionPerformed

        //ORDERREQUESTList.add()...
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(ordersidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(orderpage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_orderrequesthomepagebuttonActionPerformed
    public void loadAddItemList() {
        ITEMCODEBox.removeAllItems();//clears selection box
        ITEMLISTField.removeAll();//whenever there is a new run of the text field it will empty.
        ITEMLISTField.add(String.format("%-10s | %-12s | %-5s | %-5s | %-8s | %-8s%n", "Item Code", "Item Name", "Qty", "MOQ", "Stk Min", "Price"));
        ITEMLISTField.add("-----------------------------------------------------------------------------");
        for (Map.Entry<String, Item> entry : inventoryMap.entrySet()) {
            String key = entry.getKey();
            Item item = entry.getValue();

            String line = String.format("%-10s | %-12s | %-5d | %-5d | %-8d | %-8.2f%n", item.itemCode, item.itemName, item.qty, item.moq, item.stkMin, item.price);
            ITEMLISTField.add(line);

            ITEMCODEBox.addItem(item.itemCode);
        }

    }
    private void addqtyaddoptionspageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addqtyaddoptionspageActionPerformed

        InventoryDBManager i = new InventoryDBManager();
        inventoryMap = i.LoadInventoryTable();

        loadAddItemList();

        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(optionssidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(addqtypage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_addqtyaddoptionspageActionPerformed

    private void additemaddoptionspageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additemaddoptionspageActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(optionssidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(additempage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_additemaddoptionspageActionPerformed

    private void removeqtyremoveoptionspagebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeqtyremoveoptionspagebuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(optionssidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(removeqtypage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_removeqtyremoveoptionspagebuttonActionPerformed

    private void removeitemremoveoptionspagebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeitemremoveoptionspagebuttonActionPerformed
        // TODO add your handling code here:
        sidepanel.removeAll();
        sidepanel.add(optionssidepanel);
        sidepanel.repaint();
        sidepanel.revalidate();

        Parent.removeAll();
        Parent.add(removeitempage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_removeitemremoveoptionspagebuttonActionPerformed

    private void CREATENEWITEMButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREATENEWITEMButtonActionPerformed
        // TODO add your handling code here:
        String code = ITEMCODETextField.getText();
        String name = ITEMNAMETextField.getText();
        String supplier = SUPPLIERTextField.getText();
        Integer moq = (Integer) MOQSpinner.getValue();
        Double price = Double.parseDouble(PRICETextField.getText()); // needs to be converted to a double
        Integer min = (Integer) MINIMUMSpinner.getValue();

        //Item(String itemCode, String itemName, int qty, int moq, int stkMin, double price)
        inventoryMap.put(code, new Item(code, name, 1, moq, min, price));
        InventoryDBManager i = new InventoryDBManager();
        i.UpdateInventoryTable(inventoryMap);
        inventoryMap = i.LoadInventoryTable();

        JOptionPane.showMessageDialog(this, "Item Registered Successfully!");

        ITEMCODETextField.setText("");
        ITEMNAMETextField.setText("");
        SUPPLIERTextField.setText("");
        MOQSpinner.setValue(0);
        PRICETextField.setText("0.00");
        MINIMUMSpinner.setValue(0);
    }//GEN-LAST:event_CREATENEWITEMButtonActionPerformed

    private void ITEMADDQTYButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ITEMADDQTYButtonActionPerformed
        // TODO add your handling code here:
        InventoryDBManager i = new InventoryDBManager();
        inventoryMap = i.LoadInventoryTable(); //load hashmap before modifying qty
        Integer qty = (Integer) ITEMQTYSpinner.getValue();
        String code = (String) ITEMCODEBox.getSelectedItem();

        if (code == null || code.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select an item code.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if (qty <= 0) {
            JOptionPane.showMessageDialog(this, "Please enter a quantity greater than zero.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        Item item = inventoryMap.get(code);
        if (item == null) {
            JOptionPane.showMessageDialog(this, "Item not found in memory map.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        item.qty += qty;
        inventoryMap.put(code, item);
        i.UpdateInventoryTable(inventoryMap);
        i.LoadInventoryTable(); //Reload table
        loadAddItemList();

    }//GEN-LAST:event_ITEMADDQTYButtonActionPerformed

    private void REMOVEQTYButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REMOVEQTYButtonActionPerformed
        InventoryDBManager i = new InventoryDBManager();
        inventoryMap = i.LoadInventoryTable(); //load hashmap before modifying qty
        Integer qty = (Integer) REMOVEITEMQTYSpinner.getValue();
        String code = (String) REMOVEITEMQTYBox.getSelectedItem();

        if (code == null || code.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select an item code.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if (qty <= 0) {
            JOptionPane.showMessageDialog(this, "Please enter a quantity greater than zero.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        Item item = inventoryMap.get(code);
        if (item == null) {
            JOptionPane.showMessageDialog(this, "Item not found in memory map.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        if (!(item.qty - qty >= 0))
        {
            JOptionPane.showMessageDialog(this, "Item QTY cannot be Negative, Purchase more Item Name: " + item.itemName, " Error", JOptionPane.ERROR_MESSAGE);
        }
        else{item.qty -= qty;}
        
        inventoryMap.put(code, item);
        i.UpdateInventoryTable(inventoryMap);
        loadAddItemList();
    }//GEN-LAST:event_REMOVEQTYButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(maingui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(maingui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(maingui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(maingui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new maingui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton CREATENEWITEMButton;
    private javax.swing.JPanel Homesidepanel;
    private javax.swing.JToggleButton ITEMADDQTYButton;
    private javax.swing.JComboBox<String> ITEMCODEBox;
    private javax.swing.JTextField ITEMCODETextField;
    private java.awt.List ITEMLISTField;
    private javax.swing.JTextField ITEMNAMETextField;
    private javax.swing.JSpinner ITEMQTYSpinner;
    private javax.swing.JPasswordField LOGINPASSWORDJPasswordField;
    private javax.swing.JTextField LOGINUSERIDTextField;
    private javax.swing.JPanel Loginpage;
    private javax.swing.JPanel Loginsidepanel;
    private javax.swing.JToggleButton Logouthomesidepanelbutton;
    private javax.swing.JToggleButton Logoutinventorysidepanelbutton1;
    private javax.swing.JToggleButton Logoutoptionssidepanelbutton;
    private javax.swing.JToggleButton Logoutordersidepanelbutton;
    private javax.swing.JSpinner MINIMUMSpinner;
    private javax.swing.JSpinner MOQSpinner;
    private java.awt.List ORDERREQUESTList;
    private javax.swing.JTextField PRICETextField;
    private javax.swing.JPanel Parent;
    private java.awt.List REMOVEITEMList;
    private javax.swing.JComboBox<String> REMOVEITEMQTYBox;
    private javax.swing.JSpinner REMOVEITEMQTYSpinner;
    private javax.swing.JToggleButton REMOVEQTYButton;
    private javax.swing.JTextField RegisterNameTextField;
    private javax.swing.JPasswordField RegisterPasswordConfirmField;
    private javax.swing.JPasswordField RegisterPasswordField;
    private javax.swing.JTextField RegisterUIDTextField;
    private javax.swing.JPanel Registrationsidepanel;
    private javax.swing.JTextField SUPPLIERTextField;
    private javax.swing.JToggleButton additemaddoptionspage;
    private javax.swing.JToggleButton additemhomepagebutton;
    private javax.swing.JToggleButton additeminventorysidepanelbutton;
    private javax.swing.JToggleButton additemoptionssidepanelbutton;
    private javax.swing.JToggleButton additemordersidepanelbutton;
    private javax.swing.JPanel additempage;
    private javax.swing.JPanel addoptionspage;
    private javax.swing.JToggleButton addqtyaddoptionspage;
    private javax.swing.JPanel addqtypage;
    private javax.swing.JToggleButton homeinventorysidepanelbutton;
    private javax.swing.JToggleButton homeoptionssidepanelbutton;
    private javax.swing.JToggleButton homeordersidepanelbutton;
    private javax.swing.JPanel homepage;
    private javax.swing.JToggleButton inventoryoptionssidepanelbutton;
    private javax.swing.JToggleButton inventoryordersidepanelbutton;
    private javax.swing.JPanel inventorypage;
    private javax.swing.JPanel inventorysidepanel;
    private javax.swing.JToggleButton inventorystatushomepagebutton;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private java.awt.List list2;
    private java.awt.List list4;
    private java.awt.List list5;
    private javax.swing.JToggleButton loginloginpagebutton;
    private javax.swing.JToggleButton loginsidepanelbutton1;
    private javax.swing.JPanel optionssidepanel;
    private javax.swing.JPanel orderpage;
    private javax.swing.JToggleButton orderrequesthomepagebutton;
    private javax.swing.JToggleButton orderrequestinventorysidepanelbutton;
    private javax.swing.JToggleButton orderrequestoptionssidepanelbutton;
    private javax.swing.JPanel ordersidepanel;
    private java.awt.Panel panel1;
    private javax.swing.JToggleButton registerregistrationpagebutton;
    private javax.swing.JToggleButton registersidepanelbutton;
    private javax.swing.JPanel registrationpage;
    private javax.swing.JToggleButton removeitemhomepagebutton;
    private javax.swing.JToggleButton removeiteminventorysidepanelbutton;
    private javax.swing.JToggleButton removeitemoptionssidepanelbutton;
    private javax.swing.JToggleButton removeitemordersidepanelbutton;
    private javax.swing.JPanel removeitempage;
    private javax.swing.JToggleButton removeitemremoveoptionspagebutton;
    private javax.swing.JPanel removeoptionspage;
    private javax.swing.JPanel removeqtypage;
    private javax.swing.JToggleButton removeqtyremoveoptionspagebutton;
    private javax.swing.JPanel sidepanel;
    // End of variables declaration//GEN-END:variables
}
